export const TRACKS_LOADED = 'TRACKS_LOADED';
export const SEARCH_QUERY_CHANGED = 'SEARCH_QUERY_CHANGED';
export const PLAY_TRACK = 'PLAY_TRACK';
export const LOAD_RECENT_QUERIES = 'LOAD_RECENT_QUERIES';